### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by p3k** [alcor/itty-bitty#22]
First of all: **I love the idea and the project!**

However, in my Chrome browser I observe the following quite weird issue:

1. Open https://itty.bitty.site in a new incognito window (so no extensions get in the way) and get redirected to https://itty.bitty.site/edit – everything looks and works fine
2. Click on the _about itty bitty_ link and get redirected to [https://itty.bitty.site/#About/XQAAAA…](https://itty.bitty.site/#About/XQAAAAJNBwAAAAAAAAAeHMqHyTY4PyKmqfkwr6ooCXSIMxPQ7ojYR153HqZD3W+keVdvwyoyd+luwncAksvskG/my97qDaUEyfDGB0QDbdURMwS0L90o5EpQ7O+BMmWrcB7fs71TJEJv1I/T/JfksoiYu9CqkeO/3MjEVGWv6XhfDjWJZ9laLARogtAZtwl7FltrwO/ppSfgeKOjxCxTNdUQH9WBM3de22qOzClzeZaSsSM+/ETbHBIHe1Qc+UF7PDfY470lZNjQg3wfOam9KudUiHOOQD3Kn8FLfaae0lmdK4VHRgxpDtL1nExkdF+pzNQAIyktIv3dQUPDKhGJ61c+WBTNP6NI5AvZ0uFT+Mc2oG0mMUwwuupCrjTxxpYv3l4L3W5lBXqWDjEH+cL8VZc6xz4WwIMG5J9jaQTv1SSxJ1dLg2Z2F7iNQ0fCFI74yeqBM1koHGbscBj4GpwWuA7y/fMCu3sEzcwefjBOuUwDdDfsdxqQLnjywtBxR5qHmngo/agjHyILkZxU8IiTgJeSbjcEOWdiVxcb9tEdtZ7eDwWQcwMsQdU9A9sCnargxl1IdVsbB9dfcFTQL8OpvjdqnmFZZJ6n2cKr51FonrcrMjm68aS4Lemk+D4sRaHnN+O5BrF10BiSfjumSkvhZ0Uwu/tR35LSmtC1UmVPgRNMwWkSHZjfjEdqueqhYglmB7nHQ8TDWCTb7lJLtTdhx1btg7UWsAuNIhffUpBo+T+3oh8sg8c41WaX5JaNL19UkD2M0qFd8Sayfr0qeGXnrLrKkS0t56ckjui2rTTmUDKFup4CnEtE7fu6nGYeGSoCwGoRlYQD/SU1/GSIWfs8hSpK3KeSZgUQXk14b7dh2LaqrVKGJLja/hFcQCt2gdGD+Ml+iH+Cy0lqj3D32RSarS3k4mJyTKsGnETyXVlCbJtC7kiZ/gZ7i8ChR2hL1qWb7ZInxaHN7WVbsLxZmEIp0Bf+we6YCbg0JrLMoTqXqfx7lb4bGgIRzD4Kz+U9pve9VS4eU4c7JKX6XVLqg56dRO7Kw8MVipjdSANC/f54eQJ+YfB3RYT4eih7PAmHp62d8GiCJABN36FizyoMYLsYU+p/yfKpHOdpKSBWneDLV+ys4u9UCA/uG3KMyTZQ+AzqazInqsB7jvzSfBbPcnhh3pl9Cte+v89dGycNf72WskAJnnfgf89OxqlFj8gTqpEAwgGDFZ2DqOVnJwFqoJ1mkuxNByo2zypFTVddVxP1qeY108puAjyWmBEDFoAV/yREvgA=) – also nothing unusual here
3. Now click on the _Create a new site_ button and suddenly the page is unstyled and the scripts are missing.

    ![screen shot 2018-07-09 at 22 04 59](https://user-images.githubusercontent.com/16631/42473208-43aed1f0-83c4-11e8-924d-168cbe31f8e2.png)
In the console I see a bunch of errors:
    ```plain
    Refused to load the script 'https://itty.bitty.site/lzma/lzma_worker-min.js' because it violates the following Content Security Policy directive: "script-src 'self'".
    Refused to load the script 'https://itty.bitty.site/jquery-3.3.1.min.js' because it violates the following Content Security Policy directive: "script-src 'self'".
    Refused to load the script 'https://itty.bitty.site/data.js' because it violates the following Content Security Policy directive: "script-src 'self'".
    Refused to load the script 'https://itty.bitty.site/edit.js' because it violates the following Content Security Policy directive: "script-src 'self'".
    Refused to load the stylesheet 'https://itty.bitty.site/edit.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self'".
    Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://itty.bitty.site') does not match the recipient window's origin ('null').
    Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://itty.bitty.site') does not match the recipient window's origin ('null').
    Error in event handler for (unknown): SecurityError: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
        at getCookieValue (chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:88:33)
        at chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:52:33
        at chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:207:13
    Refused to load the stylesheet 'https://itty.bitty.site/edit.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self'".
    ```
4. From now on even other websites are not loaded correctly, e.g. https://github.com.

    ![screen shot 2018-07-09 at 22 04 13](https://user-images.githubusercontent.com/16631/42473183-311ab9d2-83c4-11e8-9eb7-b3ead7584498.png)

**Browser:** Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
**System:** macos 10.13.5 (17F77)

**Comment by SteveALee** [comment]
I've also seen the unstyled version when entering the URL in chrome address bar (on windows).t

It seem intermittent - F5 or CtRL F5 make no difference then I try again and the page comes up correctly.

Definitely 'weird'

**Comment by alcor** [comment]
This is really strange, and may be a bug in CSP? I've corrected it by not using target=_blank, but it probably warrants investigation.
